// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB48FA8w7ULWlSLag_-a73T6rXnD4F3VBY',
    appId: '1:746534385304:ios:1515f6fbdd7701f8a1c2ed',
    messagingSenderId: '746534385304',
    projectId: 'daily-postit-89948',
    storageBucket: 'daily-postit-89948.firebasestorage.app',
    iosClientId: '746534385304-osact2ht6kpo5d7efemoiq4edn23q4sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyPostit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB48FA8w7ULWlSLag_-a73T6rXnD4F3VBY',
    appId: '1:746534385304:ios:1515f6fbdd7701f8a1c2ed',
    messagingSenderId: '746534385304',
    projectId: 'daily-postit-89948',
    storageBucket: 'daily-postit-89948.firebasestorage.app',
    iosClientId: '746534385304-osact2ht6kpo5d7efemoiq4edn23q4sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyPostit',
  );
}
